### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by dylviz**
Added Privacy Policy

### CODE REVIEW

**Comment by dylviz** [comment]
@Web3Slimchance

**Review by ZorroZ77 — COMMENTED** [review]
For consistency purposes, the goal had been to include the actual content of the Privacy Policy in the body of the page (vs. download link)

**Comment by dylviz** [comment]
> For consistency purposes, the goal had been to include the actual content of the Privacy Policy in the body of the page (vs. download link)

The content is being rendered for me without downloading. Do you mean it should be written in markdown for gitbook? I see other files written in markdown

**Comment by ZorroZ77** [comment]
>  Yes, markdown would seem to be the best approach. Here the link to Code of Conduct which would conceptually be similar type of content: https://docs.graphadvocates.com/advocates-program/code-of-conduct

**Comment by dylviz** [comment]
Ok, I converted the file to use markdown txt. Should be good to merge.

**Comment by Web3Slimchance** [comment]
Renamed the page and added it to SUMMARY.md (GitBook needs this to build correctly)
I also suggested changing the headers from all caps to regular case (To be in line with our docs and gocs). Is this okay, or would they need to be re-approved? @ZorroZ77 @dylviz ?

**Comment by dylviz** [comment]
> Renamed the page and added it to SUMMARY.md (GitBook needs this to build correctly) I also suggested changing the headers from all caps to regular case (To be in line with our docs and gocs). Is this okay, or would they need to be re-approved? @ZorroZ77 @dylviz ?

yes, that's a good idea. I'll get it re-approved

**Comment by Web3Slimchance** [comment]
> > Renamed the page and added it to SUMMARY.md (GitBook needs this to build correctly) I also suggested changing the headers from all caps to regular case (To be in line with our docs and gocs). Is this okay, or would they need to be re-approved? @ZorroZ77 @dylviz ?
> 
> yes, that's a good idea. I'll get it re-approved

Should I merge, or wait for the re-approval?

**Comment by ZorroZ77** [comment]
> I think it's ok to merge. I'm actually not able to approve this one on GitHub, can only leave a comment

**Comment by Web3Slimchance** [comment]
I merged for now.

Would it also be possible to omit the following note: `[The remainder of this page is intentionally left blank.]` and to omit the inline Table of Contents? 

The pagenumbers shown in the ToC are not valid for GitBook. GitBook also has its own built-in Table of Contents. See https://docs.graphadvocates.com/community-grants/privacy-policy

**Pull request merged**
